name: practie
on:
 push:
jobs:
  first pipeline
    runs-on: ubuntu-latest
     steps:
     - name: code checkout
     - uses: actions/checkout@v4
     - name: list files
       run: echo "ls -l"
     - name: print content
       run: echo "cat README.md"
  
